const physicians = [
    {
      id: "p1",
      name: "Dr. Sarah Chen",
      specialty: "Family Medicine",
      avatar: "SC",
      bio: "15 years experience in preventive care and chronic disease management.",
      workingDays: ["Mon", "Wed", "Fri"],
    },
    {
      id: "p2",
      name: "Dr. Marcus Webb",
      specialty: "Internal Medicine",
      avatar: "MW",
      bio: "Board-certified internist specializing in complex diagnoses.",
      workingDays: ["Tue", "Thu"],
    },
    {
      id: "p3",
      name: "Dr. Amara Osei",
      specialty: "Cardiology",
      avatar: "AO",
      bio: "Fellow of the American College of Cardiology with 12 years experience.",
      workingDays: ["Mon", "Thu", "Fri"],
    },
    {
      id: "p4",
      name: "Dr. Lena Petrov",
      specialty: "Neurology",
      avatar: "LP",
      bio: "Subspecialty in headache medicine and movement disorders.",
      workingDays: ["Tue", "Wed"],
    },
  ];
  
  // In-memory bookings store — would be replaced by a database in production
  const bookings = [
    {
      id: "b1",
      physicianId: "p1",
      physicianName: "Dr. Sarah Chen",
      patientName: "Jordan Lee",
      patientEmail: "jordan.lee@email.com",
      patientPhone: "416-555-0101",
      dateStr: "Mon, May 13",
      time: "10:00 AM",
      reason: "Annual check-up / physical",
      notes: "",
      status: "confirmed",
      createdAt: "2026-05-10",
    },
    {
      id: "b2",
      physicianId: "p3",
      physicianName: "Dr. Amara Osei",
      patientName: "Maria Santos",
      patientEmail: "m.santos@email.com",
      patientPhone: "905-555-0202",
      dateStr: "Thu, May 15",
      time: "2:00 PM",
      reason: "Follow-up appointment",
      notes: "Post-procedure checkup",
      status: "pending",
      createdAt: "2026-05-11",
    },
    {
      id: "b3",
      physicianId: "p2",
      physicianName: "Dr. Marcus Webb",
      patientName: "David Kim",
      patientEmail: "dkim@email.com",
      patientPhone: "647-555-0303",
      dateStr: "Tue, May 14",
      time: "9:30 AM",
      reason: "New symptom or concern",
      notes: "Persistent fatigue and headaches for 3 weeks",
      status: "pending",
      createdAt: "2026-05-11",
    },
    {
      id: "b4",
      physicianId: "p1",
      physicianName: "Dr. Sarah Chen",
      patientName: "Aisha Noor",
      patientEmail: "anoor@email.com",
      patientPhone: "416-555-0404",
      dateStr: "Wed, May 14",
      time: "11:00 AM",
      reason: "Prescription refill",
      notes: "",
      status: "cancelled",
      createdAt: "2026-05-09",
    },
    {
      id: "b5",
      physicianId: "p4",
      physicianName: "Dr. Lena Petrov",
      patientName: "Tom Nguyen",
      patientEmail: "tnguyen@email.com",
      patientPhone: "905-555-0505",
      dateStr: "Wed, May 21",
      time: "3:00 PM",
      reason: "Specialist referral",
      notes: "GP referred for recurring migraines",
      status: "confirmed",
      createdAt: "2026-05-12",
    },
  ];
  
  module.exports = { physicians, bookings };